mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.views.i18n import javascript_catalog

from .views import *


js_info_dict_app = {
    'packages': ('polls',),
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^index/', include('polls.urls', namespace="polls")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^login/', 'django.contrib.auth.views.login'),
    url(r'^logout/$', logout_page),
    url(r'^register/$', register),
    url(r'^register/success/$', register_success),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/polls/$', javascript_catalog, js_info_dict_app),
    url(r'^jsi18n/index/$', javascript_catalog, js_info_dict_app),
]

polls/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.core.urlresolvers import reverse

from . import views


def javascript_settings():
    js_conf = {'ajax_view': reverse('ajax-view')}
    return js_conf


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^index/(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^create/$', views.CreateQuestion.as_view(), name='create_question'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditQuestion.as_view(), name='edit_question'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteQuestion.as_view(), name='delete_question'),
    url(r'^ajax/$', views.ajax_view, name='ajax-view'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

polls/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.question_text.encode('utf8')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text.encode('utf8')

polls/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Question, Choice


class QuestionCreate(forms.ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'question_single', 'class': 'yes_display bluetxt form-control-lg btn-responsive'}))

    class Meta:
        model = Question
        fields = ['question_text']


class QuestionForm(forms.ModelForm):
    question_text = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'question_single', 'class': 'yes_display bluetxt form-control-lg btn-responsive'}))
    questions = forms.ModelChoiceField(queryset=Question.objects.all(), widget=forms.Select(
        attrs={'id': 'question_dropdown', 'class': 'no_display dropdown bluetxt form-control-lg btn-responsive'}))

    class Meta:
        model = Question
        fields = ['question_text']


class ChoiceForm(forms.ModelForm):
    choice_text = forms.CharField(widget=forms.TextInput(attrs={'id': 'wrapper', 'class': 'bluetxt form-control-lg'}))

    class Meta:
        model = Choice
        fields = ['choice_text']

polls/views.py
# -*- coding: utf-8 -*-
import json
import urllib

from vanilla import CreateView, DeleteView, ListView, UpdateView
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.translation import ugettext as _

from .models import Choice, Question
from .forms import QuestionForm, QuestionCreate


class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class IndexView(LoggedInMixin, generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    model = Question
    paginate_by = 5

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(LoggedInMixin, generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(LoggedInMixin, generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': p, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


# ############### [ VANILLA VIEWS ] ###################
class ListQuestion(ListView):
    model = Question


class CreateQuestion(CreateView):
    model = Question
    form_class = QuestionCreate
    success_url = reverse_lazy('polls:index')


class EditQuestion(UpdateView):
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('polls:index')


class DeleteQuestion(DeleteView):
    model = Question
    success_url = reverse_lazy('polls:index')


# ############### [ AJAX VIEWS ] ###################
class AjaxView(generic.View):
    """
    Ajax POST Requests Handler - Dynamic Content Edition Functionality.
    """

    def post(self, request, **kwargs):
        # print "\n", 80 * "=", "\n", _('>>> IN >>>'), _('Ajax'), ('Post'), urllib.unquote_plus(
        #     self.request._body).decode(
        #     "utf-8"), "\n", 80 * "="
        # ajax_request = urllib.unquote_plus(self.request._body).decode("utf-8").split("&")
        data = {'data':'response data tekst'}
        print "RETURNING RESPONSE"
        return HttpResponse("RESPONSE")


        #
        # if len(ajax_request) > 0:
        #     question_id = int(ajax_request[0].split("=")[1].strip())
        #     action = ajax_request[1].split("=")[1].strip()
        #     value = ajax_request[2].split("=")[1].strip()
        #     q = Question.objects.get(pk=question_id)
        #
        #     # [action: DELETE CHOICE]
        #     if action == "del" and len(value) > 0:
        #         try:
        #             c = q.choice_set.get(choice_text__exact=value)
        #             c.delete()
        #             data = {"result": "ok"}
        #         except Exception:
        #             data = {"result": _("nothing to delete!")}
        #
        #     # [action: ADD CHOICE]
        #     elif action == "add":
        #         try:
        #             print q.choice_set.get(choice_text__exact=value)
        #             print "\n", _('>>>>> choice is already in database!'), "\n"
        #             data = {"result": "dup"}
        #         except Exception:
        #             q.choice_set.create(choice_text=value, votes=0)
        #             data = {"result": "ok", 'user_id': self.request.user.id, 'name': self.request.user.username}
        #
        #     # [action: VOTE +]
        #     elif action == "voteAdd":
        #         try:
        #             selected_choice = q.choice_set.get(choice_text__exact=value)
        #         except (KeyError, Choice.DoesNotExist):
        #             data = {"result": "not_added"}
        #             print "choice not found-vote not added!"
        #         else:
        #             selected_choice.votes += 1
        #             vote_count = selected_choice.votes
        #             selected_choice.save()
        #             data = {"result": "added", "vote_count": vote_count}
        #
        #     # [action: VOTE -]
        #     elif action == "voteRem":
        #         try:
        #             selected_choice = q.choice_set.get(choice_text__exact=value)
        #         except (KeyError, Choice.DoesNotExist):
        #             data = {"result": "not_added"}
        #             print "choice not found - vote not removed!"
        #         else:
        #             if selected_choice.votes < 1:
        #                 print "no votes, nothing to remove"
        #                 data = {"result": "no_votes"}
        #             else:
        #                 selected_choice.votes -= 1
        #                 vote_count = selected_choice.votes
        #                 selected_choice.save()
        #                 print "1 vote removed"
        #                 data = {"result": "removed", "vote_count": vote_count}
        #
        #     # [action: QUESTION TEXT UPDATE]
        #     elif action == "questionUpdate":
        #         try:
        #             q.question_text = value
        #             q.save()
        #         except (KeyError, Choice.DoesNotExist):
        #             data = {"result": "question_not_updated"}
        #             print "error in question update!"
        #         else:
        #             data = {"result": "updated"}
        #
        #     # [action: ALL CHOICES]
        #     elif action == "getChoices":
        #         print '= Get Choices => Question ID:', value, ' post data ->'
        #         try:
        #             choice_list = Question.objects.get(pk=value.strip())
        #             choices = choice_list.choice_set.all()
        #             print
        #         except (KeyError, Choice.DoesNotExist):
        #             data = {"result": "all_choices_failed"}
        #             print "error in retrieving all choices update!"
        #         else:
        #             response_data = ""
        #             for i in choices:
        #                 response_data += str(i) + ';' + str(i.votes) + '\n'
        #             data = {"result": "all_choices", "question_id": value, "question_txt": choice_list.question_text,
        #                     "choices": response_data}
        #     else:
        #         print "[No action recognized]"
        #
        #     responsx = json.dumps(data)
        #     print responsx
        #     print "\n", 80 * "=", "\n", _('<<< OUT <<< '), _('request'), _('successfully'), _('processed'), _(
        #         'returning'), _('response'), "\n", 80 * "=", "\n"

            # return HttpResponse(responsx)


ajax_view = AjaxView.as_view()

polls/templates/polls/detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Poll App Details{% endblock %}
{% load staticfiles %}
{% block js %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {% autoescape on %}
    <div class="jumbotron">
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}<p><strong class="lead">{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
            {% endfor %}
            <a class="btn btn-secondary" href="{% url 'polls:index' %}" >{% trans "back" %}</a>
            <input class="btn btn-primary" type="submit" value="{% trans "Vote" %} »"/>
        </form>
    </div>
                {% if latest_question_list %}
            <table id="index-tab" class="table table-striped info">
                <tr>
                    <th> {% if is_paginated %}
                        <ul class="no-padding pagination pagination-sm">
                            {% if page_obj.has_previous %}
                                <li><a class="pagi" href="/polls?page={{ page_obj.previous_page_number }}">
                                    <span>&laquo;</span>
                                </a></li>
                            {% else %}
                                <li class="disabled"><a class="pagi" href="#"><span>&laquo;</span></a></li>
                            {% endif %}
                            {% for field in page_obj.paginator.page_range %}
                                {% if field == page_obj.number %}
                                    <li class="active"><a>{{ field }}<span class="sr-only"></span></a></li>
                                {% else %}
                                    <li><a class="pagi" href="/polls?page={{ field }}">{{ field }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a class="pagi" href="/polls?page={{ page_obj.next_page_number }}">
                                    <span>&raquo;</span>
                                </a></li>
                            {% else %}
                                <li class="disabled"><a class="pagi" href="#"><span>&raquo;</span></a></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                    </th>
                    <th>{% trans "choices" %}</th>
                    <th>{% trans "time" %} & {% trans "date" %}</th>
                    <th>{% trans "action's" %}</th>
                </tr>
                {% for question in latest_question_list %}
                    <tr>
                        <td>
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        </td>
                        <td class="small">
                            <table class="table-condensed table-responsive small info">
                                {% for choice in question.choice_set.all %}
                                    <tr>
                                        <th id="thnr_{{ forloop.counter }}{{ question.id }}">
                                            {{ forloop.counter }}.
                                        </th>
                                        <th id="thch_{{ forloop.counter }}{{ question.id }}">
                                            {{ choice.choice_text }}
                                        </th>
                                        <th id="thv_{{ forloop.counter }}{{ question.id }}">
                                            <strong>{{ choice.votes }}</strong>

                                        </th>
                                        <th id="thv_2{{ forloop.counter }}{{ question.id }}">


                                            vote{{ choice.votes|pluralize }}
                                        </th>
                                    </tr>
                                {% endfor %}
                            </table>
                        </td>
                        <td>
                            {{ question.pub_date }}
                        </td>
                        <td>
                            <form method="post" action="{% url 'polls:delete_question' question.pk %}">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-sm btn-danger" value="{% trans "delete" %}"/>
                                <a class="btn btn-sm btn-info"
                                   href="{% url 'polls:edit_question' question.pk %}">{% trans "edit" %}</a>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    {% endautoescape %}
{% endblock %}

polls/templates/polls/footer.html
{% load i18n %}
{% block footer %}
    <p class="footer">
        <strong>© IDEGO 2015</strong> - {% trans "All Rights Reserved" %}.
        <strong>Django &amp; Bootstrap 4</strong> - {% trans "Jumbotron example" %} by MF.
        <button id="highcontrast" class="btn btn-secondary pull-right btn-responsive">
            {% trans "dark theme" %}
        </button>
    </p>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block title %}Poll App Home{% endblock %}
{% load staticfiles %}
{% load i18n %}
{% block js %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {% autoescape on %}
        <div class="starter-template">
            <h1>{% trans "Django 1.8 - Polls App" %}</h1>

            <p class="lead">{% trans "Application" %} {% trans "from" %} {% trans "django" %} {% trans "tutorial" %} {% trans "with added" %}
                bootstrap 4 {% trans "and" %} {% trans "login functionality" %}.</p>
        </div>
        <div>
            <a class="btn btn-lg btn-primary pull-right bt btn-responsive "
               href="{% url 'polls:create_question' %}">{% trans "Create a new question:" %}</a>
        </div>
        {% if latest_question_list %}
            {% if is_paginated %}
                <ul class="no-padding pagination pagination-sm">
                    {% if page_obj.has_previous %}
                        <li><a class="pagi" href="/polls?page={{ page_obj.previous_page_number }}">
                            <span>&laquo;</span>
                        </a></li>
                    {% else %}
                        <li class="disabled"><a class="pagi" href="#"><span>&laquo;</span></a></li>
                    {% endif %}
                    {% for field in page_obj.paginator.page_range %}
                        {% if field == page_obj.number %}
                            <li class="active"><a>{{ field }}<span class="sr-only"></span></a></li>
                        {% else %}
                            <li><a class="pagi" href="/polls?page={{ field }}">{{ field }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li><a class="pagi" href="/polls?page={{ page_obj.next_page_number }}">
                            <span>&raquo;</span>
                        </a></li>
                    {% else %}
                        <li class="disabled"><a class="pagi" href="#"><span>&raquo;</span></a></li>
                    {% endif %}
                </ul>
            {% endif %}
            <table id="index-tab" class="table table-striped info">
                <tr class="text-uppercase">
                    <th>{% trans "questions" %}</th>
                    <th>{% trans "choices" %}</th>
                    <th>{% trans "time" %}</th>
                    <th>{% trans "action's" %}</th>
                </tr>
                {% for question in latest_question_list %}
                    <tr>
                        <td>
                            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        </td>
                        <td class="small">
                            {% if question.choice_set.all|length > 0 %}
                                <table class="table-condensed table-responsive small info">
                                    {% for choice in question.choice_set.all %}
                                        <tr>
                                            <th id="thnr_{{ forloop.counter }}{{ question.id }}">
                                                {{ forloop.counter }}.
                                            </th>
                                            <th id="thch_{{ forloop.counter }}{{ question.id }}">
                                                {{ choice.choice_text }}
                                            </th>
                                            <th id="thv_{{ forloop.counter }}{{ question.id }}">
                                                <strong>{{ choice.votes }}</strong>

                                            </th>
                                            <th id="thv_2{{ forloop.counter }}{{ question.id }}">
                                                {% if choice.votes > 0 %}
                                                    {% blocktrans count counter=choice.votes %} vote
                                                    {% plural %} votes {% endblocktrans %}
                                                {% else %}
                                                    {% trans "no votes" %}
                                                {% endif %}
                                            </th>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% endif %}
                        </td>
                        <td>
                            {{ question.pub_date }}
                        </td>
                        <td>
                            <form method="post" action="{% url 'polls:delete_question' question.pk %}">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-sm btn-danger" value="{% trans "delete" %}"/>
                                <a class="btn btn-sm btn-info"
                                   href="{% url 'polls:edit_question' question.pk %}">{% trans "edit" %}</a>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% if is_paginated %}
                <div class="text-center">
                    <ul class="pagination pagination-lg">
                        {% if page_obj.has_previous %}
                            <li><a class="pagi" href="/polls?page={{ page_obj.previous_page_number }}">
                                <span>&laquo;</span>
                            </a></li>
                        {% else %}
                            <li class="disabled"><a class="pagi" href="#"><span>&laquo;</span></a></li>
                        {% endif %}
                        {% for field in page_obj.paginator.page_range %}
                            {% if field == page_obj.number %}
                                <li class="active"><a>{{ field }}<span class="sr-only"></span></a></li>
                            {% else %}
                                <li><a class="pagi" href="/polls?page={{ field }}">{{ field }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a class="pagi" href="/polls?page={{ page_obj.next_page_number }}">
                                <span>&raquo;</span>
                            </a></li>
                        {% else %}
                            <li class="disabled"><a class="pagi" href="#"><span>&raquo;</span></a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    {% endautoescape %}
{% endblock %}

polls/templates/polls/question_form.html
{% extends "base.html" %}
{% block title %}Poll App Question Form{% endblock %}
{% load staticfiles %}
{% load i18n %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'ajax/ajax_script.js' %}"></script>
{% endblock %}
{% block content %}
    {% autoescape on %}
    {% endautoescape %}
    <a href="{% url 'polls:index' %}" class="btn btn-secondary pull-right btn-responsive">{% trans "Back to Home" %}</a>
    <div class="header center">
        <h1 class="header text-center">
            {% if question %}
                {% trans "Poll App Editor Form" %}
                <input type="hidden" id="question_id" name="variable" value="{{ question.id }}"/>
            {% else %}
                {% trans "Poll App Create Question" %}
            {% endif %}
        </h1>
    </div>
    <hr/>

    <form method="post" action=".">
        <div class="xdiv">
            <div class="xleft">
                {% if question %}
                    <button id="question_button"
                            class="form-control-lg btn-responsive btn-info">{% trans "Question" %}</button>
                {% else %}
                    <label class="btn-lg btn-info btn-responsive ">{% trans "Question text:" %}</label>
                {% endif %}
            </div>
            {% csrf_token %}
            <label class="xmid">
                {% for field in form.visible_fields %}
                    {{ field }}
                    {% if field.errors %}
                        <label class="xdiv btn-danger btn">{{ field.errors }}</label>
                    {% endif %}
                {% endfor %}
            </label>

            <div class="xright">
                {% csrf_token %}
                {% if question %}
                    <input id="main_save_button" type="submit" class="form-control-lg btn-primary btn-responsive"
                           value="{% trans "edit question" %}"/>
                {% else %}
                    <input id="main_save_button" type="submit"
                           class="form-control-lg btn-success btn-responsive"
                           value="{% trans "save" %}"/>
                {% endif %}
            </div>
        </div>
    </form>

    {% if question %}
        <form class="xdiv" method="post" action="">
            {% csrf_token %}
            <div class="form-control-lg btn-lg  btn-responsive text-capitalize">{% trans "choice text:" %}</div>
            <input class="xmid bluetxt btn-responsive form-control-lg " type="text" id="ajax_test_in"/>
            <input type="submit" class="form-control-lg btn-primary btn-responsive" id="ajax_add"
                   value="{% trans "add new choice" %}"/>
        </form>
        <br/>
        <table id="choice_table" class="table choices table-hover table-active">
            <tr class="text-uppercase">
                <th class="row-1 row-Choice">{% trans "choices" %}</th>
                <th class="row-2 row-Votes">{% trans "votes" %} {% trans "and" %} {% trans "action's" %}</th>
            </tr>
            {% for choice in question.choice_set.all %}
                <tr>
                    <td>
                        <label for="choice_{{ forloop.counter0 }}"
                               class="pull-left">{{ choice.choice_text }}</label>
                        <input id="choice_{{ forloop.counter0 }}" class="clickedit tableWrapper" type="text"
                               value="{{ choice.choice_text }}"/>
                    </td>
                    <td>
                        <div class="small-padding btn btn-info">
                            <button onclick="plusFunction()" class="widther-txt addVote btn-info">+</button>
                            <label class="no-padding" id="votes_{{ forloop.counter0 }}">{{ choice.votes }}</label>
                            <button onclick="minusFunction()" class="widther-txt remVote btn-info">-</button>
                        </div>
                        <button class="rowEdit btn btn-primary">{% trans "edit" %}</button>
                        <button class="rowDelete btn btn-danger">{% trans "delete" %}</button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Poll App Results{% endblock %}
{% block content %}
    <div class="container jumbotron">
        <h1>{{ question.question_text }}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} : <strong>{{ choice.votes }}</strong> {% trans "vote" %}{{ choice.votes|pluralize }}
                </li>
            {% endfor %}
        </ul>
        <a class="btn btn-secondary" href="/index">{% trans "back" %}</a>
        <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">{% trans "Vote again?" %}</a>
    </div>
{% endblock %}